name: Build dnsmasq container

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log Level"
        default: "debug"
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/renovate.json'
      - '.github/workflows/renovate.yaml'
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/acbgbca/dnsmasq:latest